### PR TITLE
Clean up compiler warnings

### PR DESCRIPTION
**Pull request by PaulStoffregen**
Newer versions of the gcc toolchain show numerous warnings.

Hopefully none of these edits are controversial?

### CODE REVIEW

**Comment by adrianfreed** [comment]
Jeff,

I was just going to look at this carefully as I return from vacation. Paul's work is always very good, but the OSC library has to be tested against a LOT of Arduino platforms. It can take weeks. Which platforms and example files did you test before accepting the commit?

**Comment by equilet** [comment]
Only a few unfortunately and I'm unable to revert automatically.  I can revert the repository if you like.  Regarding testing, I'd contacted Paul off of Github and didn't hear back.

**Comment by adrianfreed** [comment]
No, please don’t touch this repo. until I am done syncing merging and testing (in a few weeks).

**Comment by equilet** [comment]
Will do

**Comment by gdsports** [comment]
I have been experimenting with TravisCI. You can see the .travis.yml file [here](https://github.com/gdsports/OSC/blob/master/.travis.yml). TravisCI can be used to ensure the examples compile and build under a variety of environments such as AVR, SAM, SAMD, and ESP. The script is turning out to be a lot more complicated than I thought. The [last report ](https://travis-ci.org/gdsports/OSC/builds/275416173) shows green check marks but there are still compile errors in the logs. Unless there is some interest, I will halt for now.

**Comment by PaulStoffregen** [comment]
Sorry to set off so much trouble.  Also, really sorry I'm *so far* behind on non-customer emails.

It's possible to revert git commits and just push to the repository to put everything back as it was.  I'm personally not a master of git commands, but I'm sure you could find someone who can come up with the magic command ling args reverse this.

This pull request grew out of an effort to automatically check all Arduino libs for errors and compiler warnings.  The good news is OSC compiles.  But the bad news is it generates a large number of compiler warnings, especially when multiplied by the large number of examples.

When you work on this again, please watch for compiler warnings.  With Teensy you should always see them.  I recommend turning off "verbose info while compiling" in Arduino's File > Preferences.  The verbose compiler commands generate far too much output which makes the valuable warning messages get lost like needles in a haystack.

With non-Teensy boards, please use Arduino's File > Preferences to turn on all the compiler warnings.  With Teensy they're always enabled, but Arduino's boards default to not showing the warnings.

**Comment by equilet** [comment]
Thanks Paul!

**Pull request merged**
