### PR TITLE
ESP8266 support +minor bug fixes

### PR DESCRIPTION
**Pull request by brendanmatkin**
This adds basic support for ESP8266 by:
 - excluding some oscuino methods for defined(ESP_H)
 - fixing some non-pointer type methods returning null and 
 - removing an overload of OSCData() that was causing errors
 - fixing what looked like a mistake: oscTime() returning nothing

Thanks!!

### CODE REVIEW

**Comment by adrianfreed** [comment]
thanks for your work. I can't merge as is because some changes would break existing platforms. I will look more closely at resolving these problems soon.

**Comment by brendanmatkin** [comment]
Sandeep Mistry has a version as well that may be a little more robust than
mine. I can send you the link or incorporate his changes into mine and make
a new pull request. Would you prefer one or the other?

Brendan.

**Comment by adrianfreed** [comment]
please send me the link.


I will build on your work and Sandeep's when I have an ESP8266 and can test properly.
We do major platform incorporation releases of this sort over the summer.

**Comment by brendanmatkin** [comment]
https://github.com/sandeepmistry/esp8266-OSC Here you go! Let me know if
you have any issues or need things tested. The Arduino ESP hardware stuff
is finally starting to settle and it's mostly just little bug fixes and
adding features now.

I'm running windows 8 x64 and will be running OS X soon as well if you need
help testing (I have teensys and esps and unos and attinys and a bunch of
other stuff). I'm newer to actually contributing to libraries and such so
just getting the hang of it.

Brendan.

**Comment by adrianfreed** [comment]
Pulling later 8266 code changes now and testing at CNMAT

**Comment by brendanmatkin** [comment]
Thanks let me know if I can help!

**Pull request closed without merging**
